//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABORATORIO.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public int idpersona { get; set; }
        public string nombrePersona { get; set; }
        public Nullable<int> edadPersona { get; set; }
        public string descripcionPersona { get; set; }
    }
}
